-- 코드를 입력하세요
SELECT b.AUTHOR_ID
     , a.AUTHOR_NAME
     , b.CATEGORY
     , SUM(bs.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK b
        JOIN
     AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
        JOIN
     BOOK_SALES bs ON bs.BOOK_ID = b.BOOK_ID
WHERE DATE_FORMAT(bs.SALES_DATE, '2022-01-%d') = DATE_FORMAT(bs.SALES_DATE, '%Y-%m-%d')
GROUP BY b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY 
ORDER BY b.AUTHOR_ID ASC, b.CATEGORY DESC