-- 코드를 작성해주세요
WITH CTE AS(
    SELECT ITEM_ID
         , PARENT_ITEM_ID
    FROM ITEM_TREE 
    WHERE PARENT_ITEM_ID IS NULL
)
SELECT i.ITEM_ID
     , ITEM_NAME
FROM ITEM_INFO i
        JOIN
     CTE c ON i.ITEM_ID = c.ITEM_ID
ORDER BY i.ITEM_ID