SELECT DATE_FORMAT(SALES_DATE, '2022-03-%d') AS SALES_DATE
     , PRODUCT_ID
     , USER_ID
     , SALES_AMOUNT
FROM ONLINE_SALE 
WHERE SALES_DATE = DATE_FORMAT(SALES_DATE, '2022-03-%d')

UNION

SELECT DATE_FORMAT(SALES_DATE, '2022-03-%d') AS SALES_DATE
     , PRODUCT_ID
     , NULL
     , SALES_AMOUNT
FROM OFFLINE_SALE 
WHERE SALES_DATE = DATE_FORMAT(SALES_DATE, '2022-03-%d')

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC