# -- 코드를 입력하세요
WITH CTE AS (SELECT a.CAR_ID, a.CAR_TYPE, a.DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR a
        JOIN
     CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON a.CAR_ID = b.CAR_ID
WHERE a.CAR_ID NOT IN (SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE START_DATE <= '2022-11-30' AND
                END_DATE >='2022-11-01') AND
    a.CAR_TYPE IN ('세단', 'SUV')
),
CTE2 AS (SELECT distinct a.CAR_ID
     , a.CAR_TYPE
     , ROUND((a.DAILY_FEE - (a.DAILY_FEE * (discount_rate / 100))) * 30) AS FEE
FROM CTE a
    JOIN
     CAR_RENTAL_COMPANY_DISCOUNT_PLAN b ON a.CAR_TYPE = b.CAR_TYPE
WHERE b.duration_type = '30일 이상')

SELECT *
FROM CTE2
WHERE FEE >= 500000 and FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
      