-- 코드를 입력하세요
SELECT b.USER_ID
     , b.NICKNAME
     , CONCAT(b.CITY, ' ', b.STREET_ADDRESS1, ' ', b.STREET_ADDRESS2) AS 전체주소
     , CONCAT(MID(b.TLNO, 1, 3), '-', MID(b.TLNO, 4, 4), '-', MID(b.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER b
        JOIN
(SELECT WRITER_ID, COUNT(WRITER_ID) AS WRITE_COUNT
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID) a ON a.WRITER_ID = b.USER_ID
WHERE a.WRITE_COUNT >= 3
ORDER BY b.USER_ID DESC