-- 코드를 입력하세요
SELECT YEAR(b.SALES_DATE) AS YEAR
     , MONTH(b.SALES_DATE) AS MONTH
     , COUNT(DISTINCT a.USER_ID) AS PURCHASED_USERS
     , ROUND(COUNT(DISTINCT a.USER_ID) 
     / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM USER_INFO a
        JOIN
     ONLINE_SALE b ON a.USER_ID = b.USER_ID
WHERE YEAR(a.JOINED) = 2021
GROUP BY YEAR(b.SALES_DATE), MONTH(b.SALES_DATE)
ORDER BY YEAR, MONTH