-- 코드를 입력하세요
WITH CTE AS (SELECT p.PRODUCT_ID
     , SUM(o.AMOUNT) AS TOTAL_AMOUNT
FROM FOOD_PRODUCT p
        JOIN 
     FOOD_ORDER o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE DATE_FORMAT(o.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY p.PRODUCT_ID)

SELECT a.PRODUCT_ID
     , a.PRODUCT_NAME
     , b.TOTAL_AMOUNT * a.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT a
        JOIN
     CTE b ON a.PRODUCT_ID = b.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID ASC