WITH CTE AS (
    SELECT 
        b.HISTORY_ID, 
        DATEDIFF(b.END_DATE, b.START_DATE) + 1 AS RENTAL_DAYS,
        a.CAR_TYPE,
        a.DAILY_FEE
    FROM 
        CAR_RENTAL_COMPANY_CAR a
    JOIN 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON a.CAR_ID = b.CAR_ID
    WHERE 
        a.CAR_TYPE = '트럭'
),
CTE2 AS (
    SELECT CAST(DURATION_TYPE AS UNSIGNED) AS DURATION
         , DISCOUNT_RATE
         , CAR_TYPE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE 
        CAR_TYPE = '트럭'
),
CTE3 AS (SELECT 
    a.HISTORY_ID,
    CASE
        WHEN a.RENTAL_DAYS >= c.DURATION THEN CAST((a.DAILY_FEE * (1 - c.DISCOUNT_RATE / 100)) * a.RENTAL_DAYS AS UNSIGNED)
        ELSE CAST(a.DAILY_FEE * a.RENTAL_DAYS AS UNSIGNED)
    END AS FEE
FROM 
    CTE a
    JOIN
    CTE2 c ON a.car_type = c.car_type
)
    
SELECT HISTORY_ID, MIN(FEE) AS FEE
FROM CTE3
GROUP BY HISTORY_ID
ORDER BY 
    FEE DESC, 
    HISTORY_ID DESC