-- 코드를 입력하세요
# SELECT FLAVOR
# FROM (SELECT a.FLAVOR, SUM(a.TOTAL_ORDER) + SUM(b.TOTAL_ORDER) AS TOTAL2
# FROM FIRST_HALF a
#         JOIN
#      JULY b ON a.SHIPMENT_ID = b.SHIPMENT_ID
# GROUP BY a.FLAVOR) a
# ORDER BY a.TOTAL2 DESC
# LIMIT 3


WITH CTE AS (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL1
FROM FIRST_HALF
GROUP BY FLAVOR
UNION ALL
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL2
FROM JULY
GROUP BY FLAVOR),
CTE2 AS (SELECT FLAVOR, SUM(TOTAL1) AS TOTAL
        FROM CTE
        GROUP BY FLAVOR)

SELECT FLAVOR
FROM CTE2
ORDER BY TOTAL DESC
LIMIT 3