-- 코드를 입력하세요
# SELECT HOUR(DATETIME) AS HOUR
#      , COUNT(ANIMAL_ID) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY HOUR
# ORDER BY HOUR ASC

SET @HOUR = -1;
SELECT @HOUR := @HOUR + 1
     , (SELECT COUNT(*)
        FROM ANIMAL_OUTS
        WHERE HOUR(DATETIME) = @HOUR) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23
