-- 코드를 작성해주세요
SELECT ed2.ID, ed2.GENOTYPE, ed.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA ed
        JOIN
     ECOLI_DATA ed2 ON ed.ID = ed2.PARENT_ID
WHERE ed.GENOTYPE = ed.GENOTYPE & ed2.GENOTYPE
ORDER BY ed2.ID

