-- 코드를 작성해주세요
SELECT COUNT(FISH_TYPE) AS FISH_COUNT
     , CONVERT(DATE_FORMAT(TIME, '%c'), SIGNED) AS MONTH # 숫자형으로 바꿔줘야 함!!!
FROM FISH_INFO
GROUP BY CONVERT(DATE_FORMAT(TIME, '%c'), SIGNED)
ORDER BY MONTH